### PR TITLE
nitpicks

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Review by avl — COMMENTED** [review]
Welcome, and thanks for contributing to savefile!

You've run 'cargo fmt' on the codebase, right? 

In principle I'm for having automatic code formatting, to make it easier for others to work on the code.

Also, 99% of all the changes are changes I approve of. But in some cases the code just explodes vertically. Do you know if it's possible to configure "cargo fmt" to allow slightly wider lines? Or is even that is a bad idea, maybe it's considered good form to only use the default "cargo fmt" settings?

**Comment by avl** [comment]
I'd like to add that I'm inclined to merge this as is. Just wanted to have some discussion about possible "cargo fmt" configuration before doing so!

**Comment by Uriopass** [comment]
You can configure rustfmt's line width using a `rustfmt.toml` file at the root and specifying [max width](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#max_width). Default is 100 chars.

**Comment by avl** [comment]
Closing this old PR since it is no longer relevant.

**Pull request closed without merging**
